#ifndef SHIP_DEFINER
#define SHIP_DEFINER

#define __DEBUG true

#define STEARING_SERVO_PIN 7
#define STEARING_SERVO_OFFSET 90
#define STEARING_SERVO_REVERSE false

#define MOTOR_PWM_A1_PIN 8
#define MOTOR_PWM_A2_PIN 9
#define MOTOR_PWM_B1_PIN 10
#define MOTOR_PWM_B2_PIN 11

#define ESP_RST_PIN 50

#define TEMP_AKKU_PIN 51
#define TEMP_WATER_PIN 52
#define TEMP_AIR_PIN 53

#define TRANSIS_BOTTOM_LEFT_FRONT 42
#define TRANSIS_BOTTOM_LEFT_BACK 43
#define TRANSIS_TOP_LEFT_FRONT 44
#define TRANSIS_TOP_LEFT_BACK 45
#define TRANSIS_BOTTOM_RIGH_FRONT 46
#define TRANSIS_BOTTOM_RIGH_BACK 47
#define TRANSIS_TOP_RIGH_FRONT 48
#define TRANSIS_TOP_RIGH_BACK 49

#define TFT_RS 38
#define TFT_WR 39
#define TFT_CS 40
#define TFT_RST 41
#define TOUCH_CLK 6
#define TOUCH_CS 5
#define TOUCH_MOSI_DIN 4
#define TOUCH_MISO_DOUT 3
#define TOUCH_PEN_IQR 2

#endif