# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\Mika\Documents\pyQt5 Projects\someUi.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_widget(object):
    def setupUi(self, widget):
        widget.setObjectName("widget")
        widget.resize(800, 480)
        font = QtGui.QFont()
        font.setPointSize(24)
        widget.setFont(font)
        widget.setStyleSheet("QWidget#widget {\n"
"background-color:qlineargradient(spread:pad, x1:0.0400147, y1:0.215, x2:1, y2:0.43, stop:0.237569 rgba(77, 105, 67, 255), stop:1 rgba(255, 255, 255, 255))\n"
"}\n"
"font-size: 26px;")
        self.button2 = QtWidgets.QPushButton(widget)
        self.button2.setGeometry(QtCore.QRect(400, 430, 400, 50))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.button2.setFont(font)
        self.button2.setStyleSheet("margin: 0px;\n"
"padding: opx;\n"
"border: none;\n"
"background-color: white;")
        self.button2.setObjectName("button2")
        self.button1 = QtWidgets.QPushButton(widget)
        self.button1.setGeometry(QtCore.QRect(0, 430, 400, 50))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.button1.setFont(font)
        self.button1.setStyleSheet("margin: 0px;\n"
"padding: opx;\n"
"border: none;\n"
"background-color: black;\n"
"color: white;")
        self.button1.setObjectName("button1")
        self.picWidget = QtWidgets.QWidget(widget)
        self.picWidget.setGeometry(QtCore.QRect(50, 50, 700, 380))
        self.picWidget.setObjectName("picWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.picWidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.scrollArea = QtWidgets.QScrollArea(self.picWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea.sizePolicy().hasHeightForWidth())
        self.scrollArea.setSizePolicy(sizePolicy)
        self.scrollArea.setStyleSheet("background: transparent;\n"
"margin: 0px;\n"
"border: none;\n"
"padding: 10px;")
        self.scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.scrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 658, 338))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.scrollAreaWidgetContents)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_9 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton_9.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_9.sizePolicy().hasHeightForWidth())
        self.pushButton_9.setSizePolicy(sizePolicy)
        self.pushButton_9.setMinimumSize(QtCore.QSize(250, 250))
        self.pushButton_9.setMaximumSize(QtCore.QSize(250, 250))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.pushButton_9.setFont(font)
        self.pushButton_9.setStyleSheet("background-color: green;\n"
"border-radius: 25px;")
        self.pushButton_9.setObjectName("pushButton_9")
        self.horizontalLayout.addWidget(self.pushButton_9)
        self.pushButton_11 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton_11.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_11.sizePolicy().hasHeightForWidth())
        self.pushButton_11.setSizePolicy(sizePolicy)
        self.pushButton_11.setMinimumSize(QtCore.QSize(250, 250))
        self.pushButton_11.setMaximumSize(QtCore.QSize(250, 250))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.pushButton_11.setFont(font)
        self.pushButton_11.setStyleSheet("background-color: green;\n"
"border-radius: 25px;")
        self.pushButton_11.setObjectName("pushButton_11")
        self.horizontalLayout.addWidget(self.pushButton_11)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_2.addWidget(self.scrollArea)

        self.retranslateUi(widget)
        QtCore.QMetaObject.connectSlotsByName(widget)

    def retranslateUi(self, widget):
        _translate = QtCore.QCoreApplication.translate
        widget.setWindowTitle(_translate("widget", "Form"))
        self.button2.setText(_translate("widget", "PushButton"))
        self.button1.setText(_translate("widget", "PushButton"))
        self.picWidget.setToolTip(_translate("widget", "<html><head/><body><p>asdasdasd</p></body></html>"))
        self.pushButton_9.setText(_translate("widget", "PushButton"))
        self.pushButton_11.setText(_translate("widget", "PushButton"))
